FROM node:20-alpine AS base
WORKDIR /app

COPY inmobiliaria-app/package*.json ./
RUN npm ci

FROM base AS builder
COPY inmobiliaria-app/ ./
RUN npm run build

FROM node:20-alpine AS runtime
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY inmobiliaria-app/package*.json ./

EXPOSE 3000
ENV NODE_ENV=Development
CMD ["npm", "start"]